qlpdb/qlpdb/config/urls.py
import os

from django.urls import path, include

from django.contrib import admin
from django.contrib.auth import views as auth_views

from espressodb.management.utilities.settings import PROJECT_APPS
from espressodb.management.utilities.settings import ROOT_DIR

urlpatterns = [
    path("", include("espressodb.base.urls", namespace="base")),
    path("admin/", admin.site.urls),
    path(
        "login/", auth_views.LoginView.as_view(template_name="login.html"), name="login"
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        r"documentation/",
        include("espressodb.documentation.urls", namespace="documentation"),
    ),
    path(
        r"notifications/",
        include("espressodb.notifications.urls", namespace="notifications"),
    ),
]

for app in PROJECT_APPS:
    url_file = os.path.join(ROOT_DIR, app.replace(".", "/"), "urls.py")
    if os.path.exists(url_file):
        _, app_name = app.split(".")
        if app_name == "config":
            continue
        urlpatterns.append(
            path(rf"{app_name}/", include(app + ".urls", namespace=app_name))
        )

qlpdb/qlpdb/data/urls.py
# pylint: disable=C0103
"""URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.urls import path

app_name = "data"
urlpatterns = []

qlpdb/qlpdb/graph/urls.py
# pylint: disable=C0103
"""URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.urls import path

app_name = "graph"
urlpatterns = []

qlpdb/qlpdb/tdse/urls.py
# pylint: disable=C0103
"""URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.urls import path

from qlpdb.tdse.views import TdseView, TdseSummaryView, ComparisonView

app_name = "tdse"
urlpatterns = []

urlpatterns = [
    path("summary/", TdseSummaryView.as_view(), name="Tdse Summary"),
    path("plot/", ComparisonView.as_view(), name="Tdse comparison"),
    path("detail/<int:pk>/", TdseView.as_view(), name="Tdse Detail"),
]

qlpdb/qlpdb/data/models.py
"""Models of data
"""

# Note: if you want your models to use espressodb features, they must inherit from Base

from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from espressodb.base.models import Base
from django.contrib.postgres.fields import ArrayField

class Data(Base):
    experiment = models.ForeignKey(
        "experiment.Experiment",
        on_delete=models.CASCADE,
        help_text=r"Foreign Key to `experiment`",
    )
    measurement = models.PositiveIntegerField(
        null=False,
        help_text="Increasing integer field labeling measurement number"
    )
    spin_config = ArrayField(
        models.PositiveSmallIntegerField(
            validators=[
                MaxValueValidator(1),
                MinValueValidator(0)
            ]
        ),
        help_text="Spin configuration of solution, limited to 0, 1"
    )
    chain_break_fraction = models.FloatField(
        null=False,
        help_text="Chain break fraction"
    )
    energy = models.FloatField(
        null=False,
        help_text="Energy corresponding to spin_config and QUBO"
    )
    constraint_satisfaction = models.BooleanField(
        null=False,
        help_text="Are the inequality constraints satisfied by the slacks?"
    )
    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["experiment", "measurement"], name="unique_data"
            )
        ]

qlpdb/qlpdb/experiment/models.py
"""Models of experiment
"""
from typing import List, Dict

from django.db import models
from espressodb.base.models import Base
from django.db.models import JSONField

from django.db.models import Count, Avg


class Experiment(Base):
    graph = models.ForeignKey(
        "graph.Graph", on_delete=models.CASCADE, help_text=r"Foreign Key to `graph`"
    )
    machine = models.TextField(
        null=False, blank=False, help_text="Hardware name (e.g. DW_2000Q_5)"
    )
    settings = JSONField(help_text="Store DWave machine parameters")
    settings_hash = models.TextField(
        null=False,
        blank=False,
        help_text="md5 hash of key sorted normalized machine, settings, p, dictionary",
    )
    p = models.DecimalField(
        null=False,
        max_digits=6,
        decimal_places=2,
        help_text="Coefficient of penalty term, 0 to 9999.99",
    )
    chain_strength = models.FloatField(
        null=False, help_text="Set chain strength before auto_scaling"
    )
    tag = models.TextField(
        null=False,
        blank=False,
        help_text="Tag describing the anneal schedule. (Easier to just unique with tag.)",
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["graph", "machine", "settings_hash", "p", "chain_strength", "tag"],
                name="unique_experiment",
            )
        ]

    @property
    def n_data(self) -> int:
        """Returns the number of present data entries
        """
        return self.data_set.count()

    def get_summary(self, n_entries: int = 5) -> List[Dict[str, float]]:
        """Returns a summary of solutions which fulfill the constraints.

        The returned list is sorted according to energy (ascending) and contains the
        energy and number of occurances.

        Arguments:
            n_entries: Number of different energies to be returned.
        """
        exp_data = self.data_set.all()
        satisfied_data = (
            exp_data.filter(constraint_satisfaction=True)
            .values("energy")
            .annotate(
                occurances=Count("energy"),
                chain_break_fraction=Avg("chain_break_fraction"),
            )
        )
        return sorted(list(satisfied_data[:n_entries]), key=lambda el: el["energy"])

qlpdb/qlpdb/graph/models.py
"""Models of graph
"""

# Note: if you want your models to use espressodb features, they must inherit from Base

from django.db import models
from espressodb.base.models import Base
from django.contrib.postgres.fields import ArrayField


class Graph(Base):
    tag = models.TextField(
        null=False,
        blank=False,
        help_text="Tag for graph type (e.g. Hamming(n,m) or K(n,m))",
    )
    total_vertices = models.PositiveSmallIntegerField(
        null=False, help_text="Total number of vertices in graph"
    )
    total_edges = models.PositiveSmallIntegerField(
        null=False, help_text="Total number of edges in graph"
    )
    max_edges = models.PositiveSmallIntegerField(
        null=False, help_text="Maximum number of edges per vertex"
    )
    adjacency = ArrayField(
        ArrayField(models.PositiveSmallIntegerField(null=False), size=2),
        help_text="Sorted adjacency matrix of dimension [N, 2]"
    )
    adjacency_hash = models.TextField(
        null=False,
        blank=False,
        help_text="md5 hash of adjacency list used for unique constraint"
    )
    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["adjacency_hash", "tag"], name="unique_graph"
            )
        ]

qlpdb/qlpdb/tdse/models.py
"""Models of tdse
"""

import numpy as np
from django.db import models
from espressodb.base.models import Base
from django.db.models import JSONField
from django.contrib.postgres.fields import ArrayField


class Tdse(Base):
    tag = models.TextField(null=False, help_text="User-defined tag for easy searches")
    graph = models.ForeignKey(
        "graph.Graph", on_delete=models.CASCADE, help_text=r"Foreign Key to `graph`"
    )
    ising = JSONField(help_text="Ising parameters: Jij, hi, c, energyscale")
    ising_hash = models.TextField(
        null=False, blank=False, help_text="md5 hash for Ising parameters"
    )
    offset = JSONField(
        help_text="Offset parameters: normalized time, offset, hi_for_offset, offset_min, offset_range, fill_value, anneal_curve"
    )
    offset_hash = models.TextField(
        null=False, blank=False, help_text="md5 hash for offset parameters"
    )
    solver = JSONField(help_text="Solver parameters: method, rtol, atol")
    solver_hash = models.TextField(
        null=False, blank=False, help_text="md5 hash for solver parameters"
    )
    wave = JSONField(
        help_text="Wavefunction: type (mixed or pure), temp, initial wavefunction (True or transverse)"
    )
    wave_hash = models.TextField(
        null=False, blank=False, help_text="md5 hash for wave parameters"
    )
    instance = models.FileField(upload_to="instance/", help_text="save pickled instance of class")
    solution = models.FileField(upload_to="solution/", help_text="save pickled solution")
    time = ArrayField(
        models.FloatField(null=False),
        null=False,
        help_text="Normalized time array for evolution",
    )
    prob = ArrayField(
        models.FloatField(null=False),
        null=False,
        help_text="Ising ground state probability vs. time",
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=[
                    "tag",
                    "graph",
                    "ising_hash",
                    "offset_hash",
                    "solver_hash",
                    "wave_hash",
                ],
                name="unique_tdse",
            )
        ]

qlpdb/qlpdb/experiment/views.py
from django.views.generic import DetailView
from django.views.generic.list import ListView

from qlpdb.experiment.models import Experiment

# Create your views here.


class ExperimentView(DetailView):
    """View for visualizing experiments
    """

    template_name = "experiments.html"
    model = Experiment

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        experiment = context["experiment"]  # this is the instance of experiment 1
        # experiment.objects.filter()
        return context


### Summary table
### Graph: tag,
### experiment table of parameters sorted by lowest eigenvalue and
## number of data which has eigenvalue and if constraints are violated.


class ExperimentSummaryView(ListView):
    """
    """

    template_name = "experiment-summary.html"
    model = Experiment
    ordering = ["-tag"]

qlpdb/qlpdb/tdse/views.py
from django.views.generic import DetailView, TemplateView
from django.views.generic.list import ListView

from numpy import roll

from plotly.graph_objs import Scatter
from plotly.subplots import make_subplots
from plotly.offline import plot
from plotly.express.colors import sequential

from qlpdb.tdse.models import Tdse

from qlpdb.tdse.plotting.tdse_plots import aggregate


class TdseView(DetailView):
    """View for visualizing tdse
    """

    template_name = "tdse.html"
    model = Tdse


class TdseSummaryView(ListView):
    """
    """

    template_name = "tdse-summary.html"
    model = Tdse
    ordering = ["-tag"]


class ComparisonView(TemplateView):
    """
    """

    template_name = "plot.html"
    """
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        data = aggregate()

        fig = make_subplots(subplot_titles=["Probability", "Entropy"], cols=2)

        for color, (key, val) in zip(["#1f77b4", "#ff7f0e"], data.items()):
            dt = roll(val.time, -1)[:-1] - val.time[:-1]
            s_int = (val.entropy[:-1] * dt).sum()
            fig.add_trace(
                Scatter(
                    x=val.time, y=val.prob, name=key, showlegend=False, line_color=color
                ),
                col=1,
                row=1,
            )
            fig.add_trace(
                Scatter(
                    x=val.time,
                    y=val.entropy,
                    name=f"{key:1.5f},\tInt(s(t)dt) = {s_int:1.3f}",
                    line_color=color,
                ),
                col=2,
                row=1,
            )

        context["graph"] = plot(fig, auto_open=False, output_type="div")

        return context
        """

qlpdb/qlpdb/templates/index.html
{% extends "base.html" %}
{% load static %}
{% load base_extras %}

{% block content %}
<div class="jumbotron">
    <h1>Welcome to {% project_name %}</h1>
    <h5>Here are some useful informations.</h5>
</div>
<div class="container">
    <h5>Links</h5>
    <ul>
        <li>
            <a href="https://docs.dwavesys.com/docs/latest/c_solver_1.html#anneal-schedule" target="_blank">Anneal schedule</a>
            <p> Set the following parameters</p>
            <ul>
                <li>
                    <code>anneal_schedule</code>:
                    List of tuples where first key is time and second is value of s (from 0 to 1)
                </li>
                <li>
                    <code>initial_state</code>:
                    The vector as a list of tuples where first is vec entry and second is 0 or zero
                </li>
                <li>
                    <code>reinitialize_state</code>:
                    Reinitialize the state only at the beginning of the anneal. That's probaly not important though as we will just have one read.
                </li>
                <li>
                    Also, <code>spin_reversal</code> will not work.
                </li>
        </li>
    </ul>
</div>
{% endblock %}

qlpdb/qlpdb/templates/plot.html
{% extends "base.html" %}
{% load static %}
{% load base_extras %}

{% block content %}
<div class="jumbotron">
    <h1>Here are some plots</h1>
</div>
<div class="container">
    {% if graph %}
    <div style="width:600;height:500">
    {{ graph|safe }}
    </div>
    {% endif %}
</div>
{% endblock %}

qlpdb/qlpdb/templates/tdse-summary.html
{% extends "base.html" %}
{% load static %}
{% load base_extras %}
{% load experiments_extras %}

{% block head-extra %}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
<script type="text/javascript" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>

{% endblock %}


{% block content %}
<div class="jumbotron">
    <h1>Experiment Summary</h1>
    <h5>Here are some useful informations.</h5>
    <p>Use <code>Shift-Click</code> to sort multiple columns at once.</p>
</div>
<div class="container">
        <table class="table table-hover" id="tdse-table">
          <thead>
            <tr>
              <th scope="col">Graph Tag</th>
              <th scope="col">TDSE Tag</th>
              <th scope="col">solver</th>
              <th scope="col">Offset</th>
              <th scope="col">Wave</th>
              <th scope="col"><code>P(1)</code></th>
              <th scope="col"><code>S(1)</code></th>
              <th scope="col"><code>max(S)</code></th>
            </tr>
          </thead>
          <tbody>
            {% for tdse in tdse_list %}
            <tr>
                <td>{{tdse.graph.tag}}</td>
                <td>{{tdse.tag}}</td>
                <td>
                    <ul class="text-monospace" style="font-size: 0.8rem;">
                    {% for item in tdse.solver.items %}
                    <li>{{item.0}}={{item.1}}</li>
                    {% endfor %}
                    </ul>
                </td>
                <td>
                    <ul class="text-monospace" style="font-size: 0.8rem;">
                    {% for item in tdse.offset.items %}
                    {% if item.0 != "hi_for_offset" %}<li>{{item.0}}={{item.1}}</li>{% endif %}
                    {% endfor %}
                    </ul>
                </td>
                <td>
                    <ul class="text-monospace" style="font-size: 0.8rem;">
                    {% for item in tdse.wave.items %}
                    <li>{{item.0}}={{item.1}}</li>
                    {% endfor %}
                    </ul>
                </td>
                <td>{{tdse.prob|last}}</td>
                <td>{{tdse.entropy|last}}</td>
                <td>{{tdse.entropy_max}}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
</div>

<script>
$(document).ready(function() {
    $('#tdse-table').DataTable({
    });
});
</script>

{% endblock %}

qlpdb/qlpdb/templates/tdse.html
{% extends "base.html" %}
{% load static %}
{% load base_extras %}

{% block content %}
<div class="jumbotron">
    <h1>TDSE {{ tdse.id }} details</h1>
    <h5>Here are some useful informations.</h5>
</div>
<div class="container">
    <h5>Settings</h5>
    <ul>
    </ul>
</div>
{% endblock %}