qlpdb/qlpdb/config/urls.py
import os

from django.urls import path, include

from django.contrib import admin
from django.contrib.auth import views as auth_views

from espressodb.management.utilities.settings import PROJECT_APPS
from espressodb.management.utilities.settings import ROOT_DIR

urlpatterns = [
    path("", include("espressodb.base.urls", namespace="base")),
    path("admin/", admin.site.urls),
    path(
        "login/", auth_views.LoginView.as_view(template_name="login.html"), name="login"
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        r"documentation/",
        include("espressodb.documentation.urls", namespace="documentation"),
    ),
    path(
        r"notifications/",
        include("espressodb.notifications.urls", namespace="notifications"),
    ),
]

for app in PROJECT_APPS:
    url_file = os.path.join(ROOT_DIR, app.replace(".", "/"), "urls.py")
    if os.path.exists(url_file):
        _, app_name = app.split(".")
        if app_name == "config":
            continue
        urlpatterns.append(
            path(rf"{app_name}/", include(app + ".urls", namespace=app_name))
        )

qlpdb/qlpdb/data/urls.py
# pylint: disable=C0103
"""URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.urls import path

app_name = "data"
urlpatterns = []

qlpdb/qlpdb/experiment/urls.py
# pylint: disable=C0103
"""URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.urls import path
from qlpdb.experiment.views import ExperimentView, ExperimentSummaryView

app_name = "experiment"
urlpatterns = [
    path("summary/", ExperimentSummaryView.as_view(), name="Experiment Summary"),
    path("detail/<int:pk>/", ExperimentView.as_view(), name="Experiment Detail"),
]

qlpdb/qlpdb/experiment/models.py
"""Models of experiment
"""
from typing import List, Dict

from django.db import models
from espressodb.base.models import Base
from django.db.models import JSONField

from django.db.models import Count, Avg


class Experiment(Base):
    graph = models.ForeignKey(
        "graph.Graph", on_delete=models.CASCADE, help_text=r"Foreign Key to `graph`"
    )
    machine = models.TextField(
        null=False, blank=False, help_text="Hardware name (e.g. DW_2000Q_5)"
    )
    settings = JSONField(help_text="Store DWave machine parameters")
    settings_hash = models.TextField(
        null=False,
        blank=False,
        help_text="md5 hash of key sorted normalized machine, settings, p, dictionary",
    )
    p = models.DecimalField(
        null=False,
        max_digits=6,
        decimal_places=2,
        help_text="Coefficient of penalty term, 0 to 9999.99",
    )
    chain_strength = models.FloatField(
        null=False, help_text="Set chain strength before auto_scaling"
    )
    tag = models.TextField(
        null=False,
        blank=False,
        help_text="Tag describing the anneal schedule. (Easier to just unique with tag.)",
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["graph", "machine", "settings_hash", "p", "chain_strength", "tag"],
                name="unique_experiment",
            )
        ]

    @property
    def n_data(self) -> int:
        """Returns the number of present data entries
        """
        return self.data_set.count()

    def get_summary(self, n_entries: int = 5) -> List[Dict[str, float]]:
        """Returns a summary of solutions which fulfill the constraints.

        The returned list is sorted according to energy (ascending) and contains the
        energy and number of occurances.

        Arguments:
            n_entries: Number of different energies to be returned.
        """
        exp_data = self.data_set.all()
        satisfied_data = (
            exp_data.filter(constraint_satisfaction=True)
            .values("energy")
            .annotate(
                occurances=Count("energy"),
                chain_break_fraction=Avg("chain_break_fraction"),
            )
        )
        return sorted(list(satisfied_data[:n_entries]), key=lambda el: el["energy"])

qlpdb/qlpdb/experiment/views.py
from django.views.generic import DetailView
from django.views.generic.list import ListView

from qlpdb.experiment.models import Experiment

# Create your views here.


class ExperimentView(DetailView):
    """View for visualizing experiments
    """

    template_name = "experiments.html"
    model = Experiment

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        experiment = context["experiment"]  # this is the instance of experiment 1
        # experiment.objects.filter()
        return context


### Summary table
### Graph: tag,
### experiment table of parameters sorted by lowest eigenvalue and
## number of data which has eigenvalue and if constraints are violated.


class ExperimentSummaryView(ListView):
    """
    """

    template_name = "experiment-summary.html"
    model = Experiment
    ordering = ["-tag"]

qlpdb/qlpdb/experiment/templates/experiment-summary.html
{% extends "base.html" %}
{% load static %}
{% load base_extras %}
{% load experiments_extras %}

{% block head-extra %}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
<script type="text/javascript" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>

{% endblock %}


{% block content %}
<div class="jumbotron">
    <h1>Experiment Summary</h1>
    <h5>Here are some useful informations.</h5>
    <p>Use <code>Shift-Click</code> to sort multiple columns at once.</p>
</div>
<div class="container">
        <table class="table table-hover" id="experiment-table">
          <thead>
            <tr>
              <th scope="col">Graph</th>
              <th scope="col">#Data</th>
              <th scope="col">E | N | CBF</th>
              <th scope="col">Machine</th>
              <th scope="col">Penalty</th>
              <th scope="col">Offset Tag</th>
              <th scope="col">Settings</th>
            </tr>
          </thead>
          <tbody>
            {% for experiment in experiment_list %}
            <tr>
              <td>{{experiment.graph.tag}}</td>
              <td>{{experiment.n_data}}</td>
              <td>
              {% if experiment.get_summary %}
              <table class="table table-sm text-monospace text-right"  align="right" style="font-size: 0.8rem;">
                  {% for result in experiment.get_summary %}
                  <tr>
                      <td style="border: none;">{{result.energy|floatformat:0}}</td>
                      <td style="border: none;">{{result.occurances}}</td>
                      <td style="border: none;">{{result.chain_break_fraction|floatformat:2}}</td>
                  </tr>
                  {% endfor %}
                </table>
              {% else %}
                -
              {% endif %}
              </td>
              <td>{{experiment.machine}}</td>
              <td>{{experiment.p}}</td>
              <td>{{experiment.tag}}</td>
              <td><ul class="text-monospace" style="font-size: 0.8rem;">
              {% for item in experiment.settings.items %}
              <li>{{item.0}}={{item.1}}</li>
              {% endfor %}
              </ul></td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
</div>

<script>
$(document).ready(function() {
    $('#experiment-table').DataTable({
    });
});
</script>

{% endblock %}

qlpdb/qlpdb/experiment/templates/experiments.html
{% extends "base.html" %}
{% load static %}
{% load base_extras %}

{% block content %}
<div class="jumbotron">
    <h1>Experiment {{ experiment.id }} details</h1>
    <h5>Here are some useful informations.</h5>
</div>
<div class="container">
    <h5>Settings</h5>
    <ul>
    {% for key, val in experiment.settings.items %}
        <li>{{key}} - {{val}}</li>
    {% endfor %}
    </ul>
</div>
{% endblock %}